### ISSUE TITLE
iex been blocked after start redix_pubsub

### ISSUE THREAD

**Issue by cleanyong** [whatyouhide/redix_pubsub#7] opened 2016-11-26 12:54 UTC
I use redix_pubsub in Phoenix, and also use : iex -S mix phoenix.server    to start.
The code is working fine, but the problem is after started, iex been blocked by pubsub loop. If I put the receive in another process, it does not capture the event. Is there any way to work around this?

defmodule KeyExpireHandler do

	def start_link do
		{:ok, pubsub} = Redix.PubSub.start_link()

		result = Redix.PubSub.psubscribe(pubsub, "__key*__:*", self())

		# Now, messages will be sent to the current process. Let's wait for the
		# subscription confirmation:
		receive do
		  {:redix_pubsub, ^pubsub, :psubscribed, %{pattern: "__key*__:*"}} -> IO.puts "here.."
		  	  :ok
		  aaa -> 
		      :ok1
		end

		loop()

	end

  defp loop() do
    receive do
		{:redix_pubsub, _, :pmessage, %{channel: "__keyevent@0__:expired", payload: expired_key}} ->
		    
     	   Task.async fn ->  
				IO.puts "Received a message: #{expired_key}"
           end
           loop()
    end
  end
end

**Comment by whatyouhide** [comment] 2016-11-26 13:45
Hey @cleanyong,

what is happening in your `start_link/0` is that you're spawning the PubSub process, then you're acking the subscription (`:psubscribed`) but then you're calling `loop/0`: `loop/0` is a blocking function since as it blocks to receive and calls itself recursively when a `:pmessage` message comes. By the semantics of Erlang/Elixir, this function will just never return. The problem is that you're calling `start_link/0` in a process, and it calls `loop/0` in that process so that process will block. That process could be your application's main entry point or part of the initialization of your application (for example, called by a supervisor in your app's supervision tree).

What you likely want is to spawn a new process where you will do all this work:

```elixir
def start_link() do
  spawn_link(fn ->
    # all the stuff you did in start_link/0 previously
  end)
end
```

but I advise against that because it doesn't follow OTP semantics. You're very likely better off using a GenServer or similar.

Hope I was clear, I will close the issue as it's not a problem with Redix PubSub but please feel free to keep asking questions if something is not clear, the best places are StackOverflow, [Elixir Forum](https://elixirforum.com) and the #elixir-lang channel on IRC. :)

**Closed as completed by whatyouhide** 2016-11-26 13:45 UTC
